#!/usr/bin/env bash
#
# Bootstrap script for setting up a new OSX machine
#
# This should be idempotent so it can be run multiple times.
#

# requires xcode and tools!
xcode-select -p || {
    echo_error "XCode must be installed! (run xcode-select --install)"
    exit 1
}

# update your computer
if ask "Perform latest apple update?" N; then
    echo_warn "Updating to latest apple software"
    sudo softwareupdate -i -a
else
    echo "Skipping apple update"
fi

# homebrew
if command_exists brew; then
    echo "Homebrew already installed. Getting updates..."
    brew update
    brew doctor
else
    echo 'brew must be installed! (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)")'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo ">>> Installing brew packages.."
brew bundle install --file ~/Brewfile

# sdkman
curl -s "https://get.sdkman.io?rcupdate=false" | bash


# done
echo "Bootstrapping complete"