#!/bin/sh
#
# Bootstrap script for setting up a new OSX machine
#
# This should be idempotent so it can be run multiple times.
#

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init


# requires xcode and tools!
if ! command -v xcode-select -p &> /dev/null
then
    echo "XCode must be installed! (run xcode-select --install)"
    xcode-select --install
else
    echo "Xcode already installed"
fi

# homebrew
if ! command -v brew &> /dev/null
then
    echo 'brew must be installed! (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)")'
else
    echo "Homebrew already installed. Getting updates..."
    brew update
    brew doctor
fi


echo ">>> Installing brew packages.."
brew bundle install --file ~/Brewfile

# sdkman
curl -s "https://get.sdkman.io?rcupdate=false" | bash


# done
echo "Bootstrapping complete"